#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034,SC2154

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/naive
CONF_FILE=/var/etc/naive.json

script=$(readlink "$initscript")
NAME="$(basename ${script:-$initscript})"

gen_config() {
    local listen proxy log_level
    config_get listen   "main" "listen"
    config_get proxy    "main" "proxy"

    cat > "$CONF_FILE" <<EOF
{
  "listen": "$listen",
  "proxy": "$proxy"
}
EOF
}

start_service() {
    config_load "$NAME"

    local enabled
    config_get_bool enabled "main" "enabled" 1
    [ "$enabled" -eq 1 ] || return 1

    gen_config

    echo "Starting naive"
    procd_open_instance
    procd_set_param command "$PROG" "$CONF_FILE"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param file "$CONF_FILE"
    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "$NAME"
}
